### Healthy
GET http://localhost:3000/api/health

### SignUp
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "nome": "joao",
  "senha": "123456"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "nome": "joao",
  "senha": "123456"
}

### Create Receipe
POST http://localhost:3000/api/receitas
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJOYW1lIjoiam9hbyIsImlhdCI6MTc2MzY2Njc0NywiZXhwIjoxNzYzNjY2ODA3fQ.Sx9t1yjSvzxyn5Q7AtYUOuP7YdiMHhHXSD5HkdsJONs

{
  "titulo": "Receita de Teste",
  "descricao": "Descrição da receita de teste",
  "ingredientes": [
    "Ingrediente 1",
    "Ingrediente 2"
  ],
  "modoPreparo": "Modo de preparo da receita de teste.",
  "fotoUrl": "http://exemplo.com/foto.jpg"
}